### ISSUE TITLE
YAML file not found

### ISSUE THREAD

**Issue by gusbemacbe** [scx/qalculate-flatpak#1]
Hello, 

I stopped at the subtitle `Build`. I received an error:

```
flatpak-builder "build" "io.github.qalculate.Qalculate.yaml" --force-clean --install-deps-from="flathub"
Can't load 'io.github.qalculate.Qalculate.yaml': Failed to open file “/home/gusbemacbe/io.github.qalculate.Qalculate.yaml”: No such file or directory
```

**Comment by scx** [comment]
I'm sorry if I didn't make it clear enough: you have to clone the Git repository.
To do this, use the following commands:
```
git clone --recursive "https://github.com/scx/qalculate-flatpak.git";
cd "qalculate-flatpak";
```
or
```
git clone "https://github.com/scx/qalculate-flatpak.git";
cd "qalculate-flatpak";
git submodule init;
git submodule update;
```

**Comment by gusbemacbe** [comment]
It worked very well. Thank you!

Can I remove the `qalculate-flatpak` folder as I have already installed it into Flatpak?

**Comment by scx** [comment]
> Can I remove the `qalculate-flatpak` folder as I have already installed it into Flatpak?

To be honest, I am not sure. This directory contains the repo for "qalculate-gtk", so it may be a little problem here. Maybe it would be easier if you created the actual `*.flatpak` package.
So, uninstall the current app and remove repo:
https://github.com/scx/qalculate-flatpak#uninstall
```
flatpak --user uninstall "io.github.qalculate.Qalculate"
```
```
flatpak --user remote-delete "qalculate-gtk"
```
then, create a bundle package:
```
flatpak build-bundle "repo" "qalculate.flatpak" "io.github.qalculate.Qalculate" --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
```
and finally, install it:
```
flatpak --user install "qalculate.flatpak"
```

See also:
https://docs.flatpak.org/en/latest/single-file-bundles.html#single-file-bundles

**Comment by gusbemacbe** [comment]
> ```
> flatpak build-bundle "repo" "qalculate.flatpak" "io.github.qalculate.Qalculate" --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
> ```

```
error: 'repo' is not a valid repository
```

**Comment by scx** [comment]
@gusbemacbe 
I updated README and added a single-file bundle:
https://github.com/scx/qalculate-flatpak#install-single-file-bundle
https://github.com/scx/qalculate-flatpak/releases/tag/v3.3.0+20190807

**Comment by gusbemacbe** [comment]
@scx !

GReat! But I have still the same error `error: 'repo' is not a valid repository`. What is it exactly?

**Comment by scx** [comment]
> @scx !
> 
> GReat! But I have still the same error `error: 'repo' is not a valid repository`. What is it exactly?

Before creating a [single-file bundle](https://github.com/scx/qalculate-flatpak#build-single-file-bundle), you have to create [repo](https://github.com/scx/qalculate-flatpak#create-repo).
However, it is no longer necessary to build this app on your own, because I've provided the [flatpak package for x86_64](https://github.com/scx/qalculate-flatpak/releases/download/v3.3.0%2B20190807/qalculate-gtk-3.3.0+20190807.x86_64.flatpak).

See also:
https://github.com/scx/qalculate-flatpak/releases
